services:
  # Cloudflare Tunnel
  # This service connects your local containers to the public internet securely
  # without opening ports on your router.
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: displaydeck-tunnel
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - server
      - minio
      - swagger-ui
